# Generated by Django 4.2.3 on 2023-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
