# Generated by Django 4.2.3 on 2023-08-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0003_alter_question_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('users_name', models.TextField(blank=True, null=True)),
                ('users_surname', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_platform_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('TestAnswers',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_platform_app.testanswers')),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_platform_app.question')),
            ],
        ),
    ]
