# Generated by Django 4.2.3 on 2023-08-03 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0004_alter_test_creation_date_testanswers_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='TestAnswers',
            new_name='test_answers',
        ),
    ]
