# Generated by Django 4.2.3 on 2023-08-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0005_rename_testanswers_answer_test_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=255),
        ),
    ]
