# Generated by Django 4.2.3 on 2023-08-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswers',
            name='school_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
