# Generated by Django 4.2.3 on 2023-08-08 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
