# Generated by Django 4.2.3 on 2023-08-09 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0010_test_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='UserAnswer',
        ),
        migrations.RenameModel(
            old_name='TestAnswers',
            new_name='UserTestResult',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='test_answers',
            new_name='user_test_result',
        ),
    ]
