# Generated by Django 4.2.3 on 2023-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0012_alter_test_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
