# Generated by Django 4.2.3 on 2023-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0014_usertestresult_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestresult',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
