# Generated by Django 4.2.3 on 2023-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0020_alter_test_custom_diploma_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='custom_diploma_template',
        ),
        migrations.AddField(
            model_name='test',
            name='custom_diploma_template_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
