# Generated by Django 4.2.3 on 2023-08-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('test_platform_app', '0021_remove_test_custom_diploma_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='custom_diploma_template_content',
        ),
        migrations.AddField(
            model_name='test',
            name='custom_diploma_template',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
